// <auto-generated />
using ARS.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace ARS.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20180319115938_someIdUpdatess")]
    partial class someIdUpdatess
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("ARS.Models.ClassRoom", b =>
                {
                    b.Property<long>("ClassRoomId")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("TemperatureId");

                    b.Property<bool>("available");

                    b.Property<DateTime>("end_time");

                    b.Property<bool>("is_public");

                    b.Property<int>("location_id");

                    b.Property<string>("name");

                    b.Property<DateTime>("start_time");

                    b.Property<int>("temperature_id");

                    b.HasKey("ClassRoomId");

                    b.HasIndex("TemperatureId")
                        .IsUnique();

                    b.ToTable("Classrooms");
                });

            modelBuilder.Entity("ARS.Models.Location", b =>
                {
                    b.Property<long>("LocationId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("name");

                    b.HasKey("LocationId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("ARS.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<bool>("Read");

                    b.Property<int>("RoleId");

                    b.Property<long?>("RoleId1");

                    b.Property<int>("UserId");

                    b.Property<long?>("UserId1");

                    b.HasKey("NotificationId");

                    b.HasIndex("RoleId1");

                    b.HasIndex("UserId1");

                    b.ToTable("Notification");
                });

            modelBuilder.Entity("ARS.Models.Problem", b =>
                {
                    b.Property<long>("ProblemId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ClassRoomId");

                    b.Property<long?>("ClassRoomId1");

                    b.Property<string>("Name");

                    b.HasKey("ProblemId");

                    b.HasIndex("ClassRoomId1");

                    b.ToTable("Problems");
                });

            modelBuilder.Entity("ARS.Models.Reservation", b =>
                {
                    b.Property<long>("ReservationId")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("ClassRoomId");

                    b.Property<int>("ClassroomId");

                    b.Property<DateTime>("Date");

                    b.Property<DateTime>("EndTime");

                    b.Property<int>("ProblemId");

                    b.Property<DateTime>("StartTime");

                    b.Property<int>("UserId");

                    b.Property<long?>("UserId1");

                    b.HasKey("ReservationId");

                    b.HasIndex("ClassRoomId");

                    b.HasIndex("UserId1");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("ARS.Models.Role", b =>
                {
                    b.Property<long>("RoleId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("ARS.Models.Temperature", b =>
                {
                    b.Property<long>("TemperatureId")
                        .ValueGeneratedOnAdd();

                    b.Property<float>("Celcius");

                    b.Property<int>("ClassroomId");

                    b.HasKey("TemperatureId");

                    b.ToTable("Temperature");
                });

            modelBuilder.Entity("ARS.Models.Ticket", b =>
                {
                    b.Property<long>("TicketId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<string>("Description");

                    b.Property<string>("Image");

                    b.Property<int>("ProblemId");

                    b.Property<long?>("ProblemId1");

                    b.HasKey("TicketId");

                    b.HasIndex("ProblemId1");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("ARS.Models.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("BirthDate");

                    b.Property<string>("City");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Password");

                    b.Property<int>("RoleId");

                    b.Property<string>("Street");

                    b.Property<string>("Username");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ARS.Models.ClassRoom", b =>
                {
                    b.HasOne("ARS.Models.Temperature", "Temperature")
                        .WithOne("ClassRoom")
                        .HasForeignKey("ARS.Models.ClassRoom", "TemperatureId");
                });

            modelBuilder.Entity("ARS.Models.Notification", b =>
                {
                    b.HasOne("ARS.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId1");

                    b.HasOne("ARS.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId1");
                });

            modelBuilder.Entity("ARS.Models.Problem", b =>
                {
                    b.HasOne("ARS.Models.ClassRoom", "ClassRoom")
                        .WithMany()
                        .HasForeignKey("ClassRoomId1");
                });

            modelBuilder.Entity("ARS.Models.Reservation", b =>
                {
                    b.HasOne("ARS.Models.ClassRoom", "ClassRoom")
                        .WithMany("Reservations")
                        .HasForeignKey("ClassRoomId");

                    b.HasOne("ARS.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId1");
                });

            modelBuilder.Entity("ARS.Models.Ticket", b =>
                {
                    b.HasOne("ARS.Models.Problem", "Problem")
                        .WithMany()
                        .HasForeignKey("ProblemId1");
                });
#pragma warning restore 612, 618
        }
    }
}
